#!/usr/bin/env bash
# ============================================================
# MBOpenClacky — Browser remote-debugging setup helper.
#
# The Browser tool drives a local Chrome / Edge instance over the
# Chrome DevTools Protocol (CDP). This requires the browser to be
# launched with remote debugging enabled on a fixed port. This script
# detects an installed browser, and:
#   1. prints the command to launch it with --remote-debugging-port=9222
#   2. (optional) writes a small launcher script you can reuse
#
# Usage:
#   ./scripts/install_browser.sh                 # detect + print launch cmd
#   ./scripts/install_browser.sh --write         # also write a launcher
#   ./scripts/install_browser.sh --port 9333     # custom debug port
#   ./scripts/install_browser.sh --browser edge  # force Edge
# ============================================================
set -euo pipefail

PORT=9222
WRITE=false
FORCE_BROWSER=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --port) PORT="$2"; shift 2;;
        --write) WRITE=true; shift;;
        --browser) FORCE_BROWSER="$2"; shift 2;;
        *) echo "Unknown option: $1"; exit 1;;
    esac
done

step() { printf "\033[36m>> %s\033[0m\n" "$1"; }
ok()   { printf "  \033[32m[OK]\033[0m %s\n" "$1"; }

detect_browser() {
    if [ -n "$FORCE_BROWSER" ]; then
        echo "$FORCE_BROWSER"; return
    fi
    # macOS
    if [ -x "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" ]; then
        echo "chrome-mac"; return
    fi
    if [ -x "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge" ]; then
        echo "edge-mac"; return
    fi
    # Linux
    if command -v google-chrome &>/dev/null; then echo "google-chrome"; return; fi
    if command -v chromium &>/dev/null; then echo "chromium"; return; fi
    if command -v chromium-browser &>/dev/null; then echo "chromium-browser"; return; fi
    if command -v microsoft-edge &>/dev/null; then echo "microsoft-edge"; return; fi
    # Windows (Git Bash / WSL)
    if [ -x "$LOCALAPPDATA/Google/Chrome/Application/chrome.exe" ]; then echo "chrome-win"; return; fi
    echo "none"
}

BROWSER=$(detect_browser)
step "Detected browser: $BROWSER"

case "$BROWSER" in
    chrome-mac)
        BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";;
    edge-mac)
        BIN="/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge";;
    google-chrome|chromium|chromium-browser|microsoft-edge)
        BIN="$(command -v "$BROWSER")";;
    chrome-win)
        BIN="$LOCALAPPDATA/Google/Chrome/Application/chrome.exe";;
    none)
        echo "  No supported browser found."
        echo "  Install Google Chrome or Microsoft Edge, then re-run."
        exit 1;;
esac

LAUNCH="$BIN --remote-debugging-port=$PORT --user-data-dir=$HOME/.mbopenclacky/browser-profile --no-first-run --no-default-browser-check"

step "Launch command:"
echo "  $LAUNCH"

step "Verification:"
echo "  After launching, confirm CDP is up:"
echo "    curl -s http://127.0.0.1:$PORT/json/version"

if [ "$WRITE" = true ]; then
    LAUNCHER="$HOME/.mbopenclacky/launch-browser.sh"
    mkdir -p "$HOME/.mbopenclacky"
    cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by scripts/install_browser.sh — launches a CDP-enabled browser.
exec "$BIN" --remote-debugging-port=$PORT --user-data-dir="$HOME/.mbopenclacky/browser-profile" --no-first-run --no-default-browser-check "\$@"
EOF
    chmod +x "$LAUNCHER"
    ok "Wrote launcher: $LAUNCHER"
fi

ok "Browser remote-debugging setup ready (port $PORT)."
