#!/usr/bin/env bash
# known_gaps.sh — 真话台账 (truth ledger) scanner + validator (P0-2).
#
# Usage:
#   scripts/known_gaps.sh generate   Regenerate the auto-scan section of docs/known-gaps.md
#   scripts/known_gaps.sh check      Validate ledger consistency (CI gate)
#
# Scan scope: product MoonBit code (lib/ + cmd/), excluding whitebox/blackbox
# test files. Patterns: TODO / FIXME / "not implemented" / "not yet" /
# "placeholder" / "stub". A bare `Err(` is NOT a gap by itself: Err(...) is
# MoonBit's standard error constructor and a raw scan would flag every
# legitimate error return. Err( is only reported when the same line also
# carries a stub phrase, which the patterns above already cover.
#
# Suppressions: marker hits that are legitimate domain vocabulary (not
# unfinished work) are suppressed by the rules below. Suppressed hits are
# counted and reported in the ledger header; reasons live in the ledger's
# 抑制规则 section so the suppression surface stays visible and reviewable.
set -euo pipefail
# UTF-8 locale so bash substring truncation is character-based (never splits a
# multibyte char) and grep patterns match text, not bytes.
export LC_ALL=C.UTF-8

LEDGER="docs/known-gaps.md"
BEGIN_MARK="<!-- BEGIN: auto-scan (regenerated by scripts/known_gaps.sh; do not edit) -->"
END_MARK="<!-- END: auto-scan -->"
CUR_BEGIN="<!-- BEGIN: curation -->"
CUR_END="<!-- END: curation -->"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# ── Suppression rules ────────────────────────────────────────────────────────
# A hit whose "path:text" matches a grep -E pattern below is suppressed
# (legitimate domain vocabulary, not unfinished work).
SUPPRESSIONS=(
  'lib/tui/.*placeholder'
  'lib/web/template_processor\.mbt.*[Pp]laceholder'
  'lib/i18n/i18n\.mbt.*placeholder'
  'lib/message/.*placeholder'
  'lib/client/format_anthropic\.mbt.*placeholder'
  'lib/client/format_bedrock\.mbt.*placeholder'
  'lib/client/format_openai\.mbt.*placeholder'
  'lib/web/handlers_ws\.mbt.*placeholder'
  'lib/web/handlers_meetings\.mbt.*placeholder'
  'lib/web/handlers_channels\.mbt.*placeholder'
  'lib/web/handlers_skills\.mbt.*placeholder'
  'lib/web/protocol/events\.mbt.*placeholder'
  'lib/tool/pty_marker\.mbt.*placeholder'
  'lib/tool/pty\.mbt.*placeholder'
  'lib/agent/llm_caller\.mbt.*placeholder'
  'lib/agent/image_inject\.mbt.*placeholder'
  'lib/agent/react\.mbt.*placeholder'
  'lib/agent/default_profiles\.mbt.*placeholder'
  'lib/agent/tool_executor\.mbt.*placeholder'
  'lib/channel/feishu_message_parser\.mbt.*placeholder'
  'lib/agent/todo\.mbt.*TODO'
  'lib/agent/tool_executor\.mbt.*TODO'
  # 历史规格流程引用（stubfix-XX），非未完成标记
  '.*stubfix-[0-9]+.*'
  # 检测用户文本中 TODO 的功能逻辑
  'lib/agent/compressor_helper\.mbt.*TODO'
  # 运行时状态描述（非缺口）
  '(not yet persisted|does not yet exist|has not yet completed)'
  # 真实 C 辅助文件引用（实现本体，非占位）
  '(pty_stubs\.c|time_stub\.c|tool_stubs\.c|browser_popen\.c)'
  'lib/tui/console_cp_ext\.mbt.*stub'
  # 契约探针中作为断言期望值的 CLI 提示语（非缺口）
  'cmd/selftest\.mbt.*not yet'
)
# Human-readable reasons for each rule live in docs/known-gaps.md §抑制规则.

# ── Scan ─────────────────────────────────────────────────────────────────────
# Collect marker hits from product code into "$1" (hits) and "$2" (suppressed count).
# grep -n output with multiple files: "path:line:text" (the /dev/null extra
# forces the path prefix even when xargs batches a single file). All per-line
# processing is pure-bash (no subprocess per hit) so the scan stays fast on
# every platform.
scan() {
  local hits_file="$1" count_file="$2"
  local suppressed=0
  : > "$hits_file"
  shopt -s extglob
  local line
  while IFS= read -r line; do
    local f rest lnum text markers
    f="${line%%:*}"
    rest="${line#*:}"
    lnum="${rest%%:*}"
    text="${rest#*:}"
    case "$lnum" in ''|*[!0-9]*) continue ;; esac
    markers=""
    [[ "$text" == *TODO* ]]              && markers="${markers}TODO,"
    [[ "$text" == *FIXME* ]]             && markers="${markers}FIXME,"
    [[ "$text" == *"not implemented"* || "$text" == *"Not implemented"* ]] && markers="${markers}not-implemented,"
    [[ "$text" == *"not yet"* || "$text" == *"Not yet"* ]] && markers="${markers}not-yet,"
    [[ "$text" == *placeholder* || "$text" == *Placeholder* ]] && markers="${markers}placeholder,"
    [[ "$text" == *stub* || "$text" == *Stub* ]] && markers="${markers}stub,"
    markers="${markers%,}"
    [ -z "$markers" ] && continue
    # Strip \r and surrounding whitespace; truncate; escape pipes for markdown.
    text="${text//$'\r'/}"
    text="${text##+([[:space:]])}"
    text="${text%%+([[:space:]])}"
    text="${text:0:140}"
    text="${text//|/\\|}"
    local is_suppressed=0 pat
    for pat in "${SUPPRESSIONS[@]}"; do
      if [[ "$f:$text" =~ $pat ]]; then
        is_suppressed=1
        break
      fi
    done
    if [ "$is_suppressed" -eq 1 ]; then
      suppressed=$((suppressed + 1))
    else
      printf '%s|%s|%s|%s\n' "$f" "$lnum" "$markers" "$text" >> "$hits_file"
    fi
  done < <(find lib cmd -name '*.mbt' ! -name '*_wbtest.mbt' ! -name '*_test.mbt' -print0 2>/dev/null \
      | xargs -0 grep -n -E 'TODO|FIXME|not implemented|not yet|placeholder|stub' /dev/null 2>/dev/null || true)
  shopt -u extglob
  # Deterministic ordering regardless of find/xargs batch order (byte collation).
  if [ -s "$hits_file" ]; then
    LC_ALL=C sort -t'|' -k1,1 -k2,2n "$hits_file" > "$TMP_DIR/hits_sorted"
    mv "$TMP_DIR/hits_sorted" "$hits_file"
  fi
  printf '%s\n' "$suppressed" > "$count_file"
}

# Render the auto-scan section into file "$3".
render_section() {
  local total="$1" suppressed="$2" out="$3"
  {
    echo "$BEGIN_MARK"
    echo ""
    echo "扫描范围：\`lib/\` + \`cmd/\` 产品代码（排除 \`*_wbtest.mbt\`/\`*_test.mbt\`）。模式：\`TODO\` \`FIXME\` \`not implemented\` \`not yet\` \`placeholder\` \`stub\`。裸 \`Err(\` 不计为缺口（MoonBit 标准错误构造，裸扫会命中全仓所有合法错误返回），仅当同行携带 stub 短语时经由上述模式命中。"
    echo ""
    echo "当前命中 **$total** 条（另有 $suppressed 条域术语命中被抑制，抑制规则及理由见 §抑制规则）。"
    echo ""
    echo "| 位置 | 标记 | 摘要 |"
    echo "|---|---|---|"
    # Rejoin any escaped pipes inside the excerpt (fields 4+).
    awk -F'|' '{
      excerpt = $4
      for (i = 5; i <= NF; i++) excerpt = excerpt "|" $i
      print "| " $1 ":" $2 " | " $3 " | " excerpt " |"
    }' "$TMP_DIR/hits"
    echo ""
    echo "$END_MARK"
  } > "$out"
}

# Replace the auto-scan section of "$1" with the freshly rendered one,
# writing the full new ledger to "$3". Adds the section when absent.
# Always writes via a temp file + move so target == src is safe.
rewrite_ledger() {
  local src_ledger="$1" section_file="$2" target="$3"
  if [ ! -f "$src_ledger" ]; then
    { echo "# Known Gaps（真话台账）"; echo ""; cat "$section_file"; echo ""; } > "$target"
    return
  fi
  awk -v begin="$BEGIN_MARK" -v end="$END_MARK" -v secfile="$section_file" '
    { sub(/\r$/, "") }
    $0 == begin {
      while ((getline line < secfile) > 0) print line
      close(secfile)
      in_section = 1
      next
    }
    $0 == end { in_section = 0; next }
    !in_section { print }
  ' "$src_ledger" > "$TMP_DIR/ledger_new"
  if grep -q -F "$BEGIN_MARK" "$src_ledger"; then
    mv "$TMP_DIR/ledger_new" "$target"
  else
    { cat "$src_ledger"; echo ""; cat "$section_file"; echo ""; } > "$TMP_DIR/ledger_new"
    mv "$TMP_DIR/ledger_new" "$target"
  fi
}

do_generate() {
  scan "$TMP_DIR/hits" "$TMP_DIR/count"
  local total suppressed
  total="$(wc -l < "$TMP_DIR/hits" | tr -d ' ')"
  suppressed="$(cat "$TMP_DIR/count")"
  render_section "$total" "$suppressed" "$TMP_DIR/section"
  rewrite_ledger "$LEDGER" "$TMP_DIR/section" "$LEDGER"
  echo "Regenerated auto-scan section: $total hits ($suppressed suppressed)."
}

do_check() {
  local fail=0
  scan "$TMP_DIR/hits" "$TMP_DIR/count"
  local total suppressed
  total="$(wc -l < "$TMP_DIR/hits" | tr -d ' ')"
  suppressed="$(cat "$TMP_DIR/count")"
  # 1. Auto-scan section must match a fresh regeneration byte-for-byte.
  render_section "$total" "$suppressed" "$TMP_DIR/section"
  rewrite_ledger "$LEDGER" "$TMP_DIR/section" "$TMP_DIR/ledger_expected"
  if ! diff -u "$LEDGER" "$TMP_DIR/ledger_expected" > "$TMP_DIR/diff.out"; then
    echo "::error::docs/known-gaps.md auto-scan section is stale. Run: scripts/known_gaps.sh generate" >&2
    head -80 "$TMP_DIR/diff.out" >&2
    fail=1
  fi
  # 2. Curated table (between CUR markers): location -> status pairs.
  awk -v cb="$CUR_BEGIN" -v ce="$CUR_END" '
    { sub(/\r$/, "") }
    $0 == cb { in_cur = 1; next }
    $0 == ce { in_cur = 0; next }
    in_cur && /^\|/ {
      line = $0
      gsub(/^ *\| * */, "", line)
      gsub(/ *\| *$/, "", line)
      n = split(line, cols, /\|/)
      loc = cols[1]; gsub(/`/, "", loc)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", loc)
      status = cols[2]
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", status)
      if (loc ~ /^(lib|cmd)\/.*\.mbt:[0-9]+$/) print loc "\t" status
    }
  ' "$LEDGER" > "$TMP_DIR/curated_pairs" || true
  # Scan hits -> "path:line" list.
  awk -F'|' '{ gsub(/^[[:space:]]+|[[:space:]]+$/, "", $1); gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2); print $1 ":" $2 }' \
    "$TMP_DIR/hits" > "$TMP_DIR/hit_locs"
  # 2a. Every scan hit needs exactly one curated row.
  while IFS= read -r loc; do
    [ -z "$loc" ] && continue
    n="$(awk -F'\t' -v l="$loc" '$1 == l' "$TMP_DIR/curated_pairs" | wc -l | tr -d ' ')"
    if [ "$n" -eq 0 ]; then
      echo "::error::scan hit '$loc' has no curated row in $LEDGER (add: classification/status/deliverable)" >&2
      fail=1
    elif [ "$n" -gt 1 ]; then
      echo "::error::scan hit '$loc' has $n curated rows (exactly one required)" >&2
      fail=1
    fi
  done < "$TMP_DIR/hit_locs"
  # 2b. Curated rows must reference live hits (open) or existing files (fixed/retracted).
  while IFS=$'\t' read -r loc status; do
    [ -z "$loc" ] && continue
    case "$status" in
      open)
        if ! grep -qxF "$loc" "$TMP_DIR/hit_locs"; then
          echo "::error::curated row '$loc' (status=$status) no longer matches a scan hit — update its status to fixed/retracted" >&2
          fail=1
        fi
        ;;
      fixed|retracted)
        f="${loc%%:*}"
        if [ ! -f "$f" ]; then
          echo "::error::curated row '$loc' (status=$status) references a file that no longer exists" >&2
          fail=1
        fi
        ;;
      *)
        echo "::error::curated row '$loc' has invalid status '$status' (expected open|fixed|retracted)" >&2
        fail=1
        ;;
    esac
  done < "$TMP_DIR/curated_pairs"
  if [ "$fail" -eq 0 ]; then
    echo "known-gaps ledger consistent: $total live hits, $(wc -l < "$TMP_DIR/curated_pairs" | tr -d ' ') curated rows."
  fi
  exit "$fail"
}

case "${1:-}" in
  generate) do_generate ;;
  check) do_check ;;
  *) echo "usage: $0 {generate|check}" >&2; exit 2 ;;
esac
